SUPABASE_URL = "https://fjqowpuzenqraugcmmtp.supabase.co/rest/v1/"
SUPABASE_KEY = "sb_publishable_O-0SX3AeX1N__cHzRP74rA_TmwZVPL3"
SENDGRID_API_KEY = "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"
TOKEN_PEPPER = "j70GY{R&0Dukl9.d1l92IxJ*eOs!)7&3"
